apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-user: AgAAA...
    admin-password: AgBBB...
