apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-gateway
  namespace: observability
spec:
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
    processors:
      batch: {}
      spanmetrics:
        metrics_exporter: prometheus
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      loki:
        endpoint: https://lokistack-gateway-http.openshift-logging.svc:8080/loki/api/v1/push
        headers:
          X-Scope-OrgID: application
      otlp/jaeger:
        endpoint: jaeger-collector.observability.svc:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, spanmetrics]
          exporters: [otlp/jaeger]
        metrics:
          receivers: [otlp]
          processors: [spanmetrics]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki]
