apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/luissobrinhoeds/observability
    targetRevision: HEAD
    path: operators
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
